'use strict'

// Constants
export const PENDING_CONSIDERATION = 'PENDING_CONSIDERATION'
export const REJECTED = 'REJECTED'
export const ACCEPTED = 'ACCEPTED'
export const CURRENT_SMALLEST = 'CURRENT_SMALLEST'

// Actions
export const PICK_SMALLEST_FINISH_TIME = 'PICK_SMALLEST_FINISH_TIME'
export const DELETE_INCOMPATIBLES = 'DELETE_INCOMPATIBLES'
export const ACCEPT_CURRENT = 'ACCEPT_CURRENT'
